### ISSUE TITLE
Raising exceptions after catching FieldSet-related exceptions

### ISSUE THREAD

**Issue by puentesarrin** [bodbdigr/restea#33]
Hi Valery!

Restea is currenly raising `Error` and `ConfigurationError` when there is something wrong in payload request or with fields configured themselves but those are converted into `RestError`-subclassed exceptions.
https://github.com/bodbdigr/restea/blob/d0dbf7b/restea/resource.py#L201-L204

What is weird is the `RestError`-subclassed exceptions are being initialized passing the same catched instance of `Error` or `ConfigurationError`, which are actually not serializable, even for default formatter.

Do you think we can just use something like the following?
```
try:
    return self.fields.validate(payload_data)
except fields.FieldSet.Error as e:
    raise errors.BadRequestError(str(e))
except fields.FieldSet.ConfigurationError as e:
    raise errors.ServerError(str(e))
```

Thanks!

**Comment by bodbdigr** [comment]
@puentesarrin cool, could be. would you add it? feel free to submit a PR
